### PR TITLE
Remove dependency on Py package

### LINKED ISSUE #6: Security vulnerability in Py
Hi, 
thanks for taking care of this library;

One of static analysis tools on my pipeline raised an alert due to [the vulnerability found in Py](https://github.com/advisories/GHSA-w596-4wvx-j9j6) , and it's also used by retry2 package;

I am wondering if could be possible to remove  the [py](https://pypi.org/project/py/) from the [requirements.txt](https://github.com/eSAMTrade/retry/blob/5444a68944b3c7c4183384aade25b2988f4741a6/requirements.txt#L2) as it's not actually used here, the Py seems to be deprecated and it has quite high CVE.

Best regards,
Timo

### PR DESCRIPTION
**Pull request by pshchelo**
this package is not actually used in the code of this project

Closes #6

### CODE REVIEW

**Comment by i540608** [comment]
@pshchelo many thanks for tackling the issue

**Comment by wells** [comment]
@asuiu and @marian-rusu. Pretty please merge and tag a release.

**Comment by i540608** [comment]
@asuiu @marian-rusu Hi, could you take a look of this PR? It would help me to fix failing security scanners on my project;

**Comment by mcormier** [comment]
Looking forward to 0.9.5 that removes this dependency.

**Comment by asuiu** [comment]
Successfully published the release to PyPi: https://pypi.org/project/retry2/#history

@pshchelo - thanks for contribution!

++@cc: @i540608 @wells @mcormier @mcormier

**Pull request merged**
